stages:
  - build
  - build-image
  - test

variables:
  DOCKER_HOST: "tcp://server-custom-dind.custom-dind:2375"
  # Move cargo data into the project directory so it can be cached by the runner
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  RUST_BACKTRACE: "1"
  CARGO_INCREMENTAL: "0"

build-image:
  stage: build
  image: docker:27-cli
  script:
    - export COMMIT_SHA=$(git rev-parse --short HEAD)
    - echo "COMMIT_SHA=$COMMIT_SHA" >> build.env
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - echo "Building Python + Docker client image"
    # Build
    ## Builder
    - docker build --target builder -t ${CI_REGISTRY_IMAGE}:builder_${COMMIT_SHA} .
    - docker build --target builder -t ${CI_REGISTRY_IMAGE}:builder_latest        .
    ## App
    - docker build -t ${CI_REGISTRY_IMAGE}:app_${COMMIT_SHA} .
    - docker build -t ${CI_REGISTRY_IMAGE}:app_latest        .
    # Push
    ## Builder
    - docker push     ${CI_REGISTRY_IMAGE}:builder_${COMMIT_SHA}
    - docker push     ${CI_REGISTRY_IMAGE}:builder_latest
    ## App
    - docker push     ${CI_REGISTRY_IMAGE}:app_${COMMIT_SHA}
    - docker push     ${CI_REGISTRY_IMAGE}:app_latest
    # Test
    - docker run      ${CI_REGISTRY_IMAGE}:app_${COMMIT_SHA} test-plan-doc-gen --help
    - docker run      ${CI_REGISTRY_IMAGE}:app_latest        test-plan-doc-gen --help
  artifacts:
    reports:
      dotenv: build.env
  tags:
    - dind-amd

test-image-app:
  stage: test
  # Variable comes from artifacts->VARIABLE_NAME
  image: ${CI_REGISTRY_IMAGE}:app_${COMMIT_SHA}
  needs:
    - job: build-image
      artifacts: true
  script:
    - uname -a 
    - test-plan-doc-gen --help
  tags:
    - dind-amd

test-image-builder:
  stage: test
  # Variable comes from artifacts->VARIABLE_NAME
  image: ${CI_REGISTRY_IMAGE}:builder_${COMMIT_SHA}
  needs:
    - job: build-image
      artifacts: true
  script:
    - uname -a 
  tags:
    - dind-amd


default:
  # Use the commit reference slug (branch/tag name) as the cache key
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      # Cache the cargo home directory which contains registries and bins
      - .cargo
      # Cache the build artifacts directory
      - target
    # This ensures the cache is available to all jobs in the pipeline
    policy: pull-push

ci:
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add rustfmt
    - rustup component add clippy
  image: rust:latest
  stage: build
  script:
    - cargo fmt -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo build --release
    - cargo test --release --verbose
  artifacts:
    paths:
      - target/release/test-plan-doc-gen
    expire_in: 1 day
  coverage: '/(\d+\.\d+)% coverage/'
  allow_failure: false
