[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tpdg-requirements"
version = "0.1.0"
description = "Requirements documentation support for Test Plan Documentation Generator"
dependencies = ["strictdoc"]

[project.optional-dependencies]
requirements = ["strictdoc"]
