= {{ title }}
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:icons: font

[cols="1,3"]
|===
| Document ID | {{ document_id }}
| Version | {{ version }}
| Date | {{ date }}
| Project | {{ project_name }}
{% if author -%}
| Author | {{ author }}
{% endif -%}
| Software Level | {{ software_level }}
|===

<<<

== Document Purpose

This Software Verification Plan describes the verification strategy and procedures used to satisfy the verification objectives for Design Assurance Level {{ software_level }} software. It establishes the approach for demonstrating that the software requirements are satisfied and that the software does not contain errors.

== Organization and Independence

=== Development Organization

{{ organization.development_team | strip }}

=== Verification Organization

{{ organization.verification_team | strip }}

=== Independence

{{ organization.independence_statement | strip }}

<<<

== Verification Methods

The following verification methods will be employed to satisfy the DO-178C objectives:

{% for method in verification_methods -%}
=== {{ method.method }}

{{ method.description | strip }}

{% if method.applicability -%}
*Applicability:* {{ method.applicability | strip }}
{% endif %}
{% endfor %}

<<<

== Verification Environment

=== Environment Description

{{ verification_environment.test_environment_description | strip }}

{% if verification_environment.hardware -%}
=== Hardware

The verification environment includes the following hardware:

{% for hw in verification_environment.hardware -%}
* {{ hw }}
{% endfor %}
{% endif %}

{% if verification_environment.software_tools -%}
=== Software Tools

The following tools are used for verification activities:

[cols="2,3,1"]
|===
| Tool | Purpose | Qualification Required

{% for tool in verification_environment.software_tools -%}
| {{ tool.name }}
| {{ tool.purpose }}
| {% if tool.qualification_required %}Yes{% else %}No{% endif %}

{% endfor -%}
|===
{% endif %}

<<<

== Transition Criteria

The following criteria must be met to transition between software lifecycle phases:

{% for tc in transition_criteria -%}
=== {{ tc.phase }}

{% for criterion in tc.criteria -%}
* {{ criterion }}
{% endfor %}
{% endfor %}

{% if partitioning_verification -%}
<<<

== Partitioning Verification

{{ partitioning_verification | strip }}
{% endif %}

{% if compiler_assumptions -%}
<<<

== Compiler and Linker Assumptions

{{ compiler_assumptions | strip }}
{% endif %}

{% if reverification -%}
<<<

== Reverification Methods

=== Reverification Strategy

{{ reverification.strategy | strip }}

{% if reverification.impact_analysis_process -%}
=== Impact Analysis Process

{{ reverification.impact_analysis_process | strip }}
{% endif %}
{% endif %}

{% if previously_developed_software -%}
<<<

== Previously Developed Software

{{ previously_developed_software | strip }}
{% endif %}

<<<

{{ test_cases_md }}

<<<

== Approval

This Software Verification Plan has been reviewed and approved by:

[cols="1,2,2,1"]
|===
| Role | Name | Signature | Date

| Verification Manager
|
|
|

| Software Manager
|
|
|

| Quality Assurance
|
|
|

|===

<<<

*End of Document*
