#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

echo "=========================================="
echo "E2E Output Verification Script"
echo "=========================================="
echo ""
echo "This script verifies that the output files generated by the E2E tests"
echo "match the expected output files in the repository."
echo ""

# Build the project first
echo "Building project..."
cargo build --release
echo ""

# Array to track test results
declare -a PASSED_TESTS=()
declare -a FAILED_TESTS=()

# Function to run a test and compare outputs
run_test() {
    local test_name="$1"
    local output_file="$2"
    local expected_file="$3"
    shift 3
    local cmd=("$@")
    
    echo "----------------------------------------"
    echo "Running: $test_name"
    echo "----------------------------------------"
    
    # Create temporary directory for this test
    local tmp_dir=".tmp/verify-e2e-${test_name}"
    mkdir -p "$tmp_dir"
    
    # Run the command
    echo "Command: ${cmd[*]}"
    if "${cmd[@]}" > "$tmp_dir/stdout.log" 2> "$tmp_dir/stderr.log"; then
        echo "✓ Command executed successfully"
    else
        echo "✗ Command failed with exit code $?"
        cat "$tmp_dir/stderr.log"
        FAILED_TESTS+=("$test_name (execution failed)")
        return 1
    fi
    
    # Check if output file was created
    if [[ ! -f "$output_file" ]]; then
        echo "✗ Output file not created: $output_file"
        FAILED_TESTS+=("$test_name (no output file)")
        return 1
    fi
    
    # Compare with expected file
    if diff -u "$expected_file" "$output_file" > "$tmp_dir/diff.txt"; then
        echo "✓ Output matches expected file"
        PASSED_TESTS+=("$test_name")
        return 0
    else
        echo "✗ Output differs from expected file"
        echo "Diff saved to: $tmp_dir/diff.txt"
        echo "First 50 lines of diff:"
        cat "$tmp_dir/diff.txt"
        FAILED_TESTS+=("$test_name (output mismatch)")
        return 1
    fi
}

# Test 1: Markdown output (test-e2e-markdown equivalent)
echo "========================================"
echo "Test 1: Markdown Output"
echo "========================================"
echo ""

# First generate test cases using multiple-by-type mode
mkdir -p .tmp/verify-e2e-markdown
./target/release/tpdg \
    --format md \
    --output .tmp/verify-e2e-markdown/test_cases.md \
    --multiple-by-type .type \
    ./data/verification_methods \
    ./data/test_case/filter_test_01_TC.yml \
    ./data/test_case/filter_test_02_AN.yml \
    ./data/test_case/filter_test_03_IN.yml \
    ./data/test_case/filter_test_04_DM.yml \
    ./data/test_case/gsma_4.4.2.2_TC.yml \
    ./data/test_case/gsma_4.4.2.3_TC.yml \
    ./data/test_case/gsma_4.4.2.4_AN.yml \
    ./data/test_case/gsma_4.4.2.5_DM.yml \
    ./data/test_case/gsma_4.4.2.6_IN.yml \
    > .tmp/verify-e2e-markdown/stdout1.log 2>&1

# Process the test cases file (same sed operations as Makefile)
sed 's/^\(## \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-markdown/test_cases.md | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-markdown/test_cases_fixed.tmp
perl -0777 -pe 's/\n+$/\n/' .tmp/verify-e2e-markdown/test_cases_fixed.tmp > .tmp/verify-e2e-markdown/test_cases_fixed.md

# Create data file with test cases
echo "test_cases_md: |" > .tmp/verify-e2e-markdown/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-markdown/test_cases_fixed.md >> .tmp/verify-e2e-markdown/data_with_test_cases.yml
cat ./data/container/data.yml >> .tmp/verify-e2e-markdown/data_with_test_cases.yml

# Render the container template using single mode
run_test "markdown-output" \
    "./data/output.actual.md" \
    "./data/output.expected.md" \
    ./target/release/tpdg \
    --format md \
    --output ./data/output.actual.md \
    --single \
    ./data/container/schema.json \
    ./data/container/template.j2 \
    .tmp/verify-e2e-markdown/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-markdown
echo ""

# Test 2: AsciiDoc Test Plan Output
echo "========================================"
echo "Test 2: AsciiDoc Test Plan Output"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-test-plan-asciidoc
./target/release/tpdg \
    --format adoc \
    --output .tmp/verify-e2e-test-plan-asciidoc/test_cases.adoc \
    --multiple-by-type .type \
    ./data/verification_methods \
    ./data/test_case/filter_test_01_TC.yml \
    ./data/test_case/filter_test_02_AN.yml \
    ./data/test_case/filter_test_03_IN.yml \
    ./data/test_case/filter_test_04_DM.yml \
    ./data/test_case/gsma_4.4.2.2_TC.yml \
    ./data/test_case/gsma_4.4.2.3_TC.yml \
    ./data/test_case/gsma_4.4.2.4_AN.yml \
    ./data/test_case/gsma_4.4.2.5_DM.yml \
    ./data/test_case/gsma_4.4.2.6_IN.yml \
    > .tmp/verify-e2e-test-plan-asciidoc/stdout1.log 2>&1

sed 's/^\(== \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-test-plan-asciidoc/test_cases.adoc | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-test-plan-asciidoc/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-test-plan-asciidoc/test_cases_fixed.tmp)" > .tmp/verify-e2e-test-plan-asciidoc/test_cases_fixed.adoc

echo "test_cases_md: |" > .tmp/verify-e2e-test-plan-asciidoc/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-test-plan-asciidoc/test_cases_fixed.adoc >> .tmp/verify-e2e-test-plan-asciidoc/data_with_test_cases.yml
cat ./data/container/data.yml >> .tmp/verify-e2e-test-plan-asciidoc/data_with_test_cases.yml

run_test "asciidoc-test-plan" \
    "./data/test_plan_output.actual.adoc" \
    "./data/test_plan_output.expected.adoc" \
    ./target/release/tpdg \
    --format adoc \
    --output ./data/test_plan_output.actual.adoc \
    --single \
    ./data/container/schema.json \
    ./data/container/template_asciidoc.adoc \
    .tmp/verify-e2e-test-plan-asciidoc/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-test-plan-asciidoc
echo ""

# Test 3: AsciiDoc Test Results Output
echo "========================================"
echo "Test 3: AsciiDoc Test Results Output"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-test-results-asciidoc
./target/release/tpdg \
    --format adoc \
    --output .tmp/verify-e2e-test-results-asciidoc/test_cases.adoc \
    --multiple-by-type .type \
    ./data/verification_methods \
    ./data/test_results/sample_gsma_4.4.2.2_TC.yml \
    ./data/test_results/sample_gsma_4.4.2.3_TC.yml \
    ./data/test_results/sample_gsma_4.4.2.4_AN.yml \
    ./data/test_results/sample_gsma_4.4.2.5_DM.yml \
    ./data/test_results/sample_gsma_4.4.2.6_IN.yml \
    > .tmp/verify-e2e-test-results-asciidoc/stdout1.log 2>&1

sed 's/^\(== \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-test-results-asciidoc/test_cases.adoc | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-test-results-asciidoc/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-test-results-asciidoc/test_cases_fixed.tmp)" > .tmp/verify-e2e-test-results-asciidoc/test_cases_fixed.adoc

echo "test_cases_md: |" > .tmp/verify-e2e-test-results-asciidoc/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-test-results-asciidoc/test_cases_fixed.adoc >> .tmp/verify-e2e-test-results-asciidoc/data_with_test_cases.yml
cat ./data/test_results/container_data.yml >> .tmp/verify-e2e-test-results-asciidoc/data_with_test_cases.yml

run_test "asciidoc-test-results" \
    "./data/test_results_output.actual.adoc" \
    "./data/test_results_output.expected.adoc" \
    ./target/release/tpdg \
    --format adoc \
    --output ./data/test_results_output.actual.adoc \
    --single \
    ./data/test_results/container_schema.json \
    ./data/test_results/container_template_asciidoc.adoc \
    .tmp/verify-e2e-test-results-asciidoc/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-test-results-asciidoc
echo ""

# Test 4: Markdown Test Results Output
echo "========================================"
echo "Test 4: Markdown Test Results Output"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-test-results-md
./target/release/tpdg \
    --format md \
    --output .tmp/verify-e2e-test-results-md/test_cases.md \
    --multiple-by-type .type \
    ./data/verification_methods \
    ./data/test_results/sample_gsma_4.4.2.2_TC.yml \
    ./data/test_results/sample_gsma_4.4.2.3_TC.yml \
    ./data/test_results/sample_gsma_4.4.2.4_AN.yml \
    ./data/test_results/sample_gsma_4.4.2.5_DM.yml \
    ./data/test_results/sample_gsma_4.4.2.6_IN.yml \
    > .tmp/verify-e2e-test-results-md/stdout1.log 2>&1

sed 's/^\(## \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-test-results-md/test_cases.md | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-test-results-md/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-test-results-md/test_cases_fixed.tmp)" > .tmp/verify-e2e-test-results-md/test_cases_fixed.md

echo "test_cases_md: |" > .tmp/verify-e2e-test-results-md/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-test-results-md/test_cases_fixed.md >> .tmp/verify-e2e-test-results-md/data_with_test_cases.yml
cat ./data/test_results/container_data.yml >> .tmp/verify-e2e-test-results-md/data_with_test_cases.yml

run_test "markdown-test-results" \
    "./data/test_results_output.actual.md" \
    "./data/test_results_output.expected.md" \
    ./target/release/tpdg \
    --format md \
    --output ./data/test_results_output.actual.md \
    --single \
    ./data/test_results/container_schema.json \
    ./data/test_results/container_template.j2 \
    .tmp/verify-e2e-test-results-md/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-test-results-md
echo ""

# Test 5: Input Data Markdown Output
echo "========================================"
echo "Test 5: Input Data Markdown Output"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-input-data
./target/release/tpdg \
    --format md \
    --output .tmp/verify-e2e-input-data/test_cases.md \
    --multiple-by-type .type \
    ./data/input_data/verification_methods \
    ./data/input_data/test_case/TEST_PASSING_001.yml \
    ./data/input_data/test_case/TEST_FAILING_002.yml \
    ./data/input_data/test_case/gsma_4.4.2.2_TC.yml \
    ./data/input_data/test_case/gsma_4.4.2.3_TC.yml \
    > .tmp/verify-e2e-input-data/stdout1.log 2>&1

sed 's/^\(## \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-input-data/test_cases.md | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-input-data/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-input-data/test_cases_fixed.tmp)" > .tmp/verify-e2e-input-data/test_cases_fixed.md

echo "test_cases_md: |" > .tmp/verify-e2e-input-data/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-input-data/test_cases_fixed.md >> .tmp/verify-e2e-input-data/data_with_test_cases.yml
cat ./data/input_data/container/data.yml >> .tmp/verify-e2e-input-data/data_with_test_cases.yml

run_test "input-data-markdown" \
    "./data/input_data/output.actual.md" \
    "./data/input_data/output.expected.md" \
    ./target/release/tpdg \
    --format md \
    --output ./data/input_data/output.actual.md \
    --single \
    ./data/input_data/container/schema.json \
    ./data/input_data/container/template.j2 \
    .tmp/verify-e2e-input-data/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-input-data
echo ""

# Test 6: Input Data AsciiDoc Test Plan
echo "========================================"
echo "Test 6: Input Data AsciiDoc Test Plan"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-input-data-test-plan-asciidoc
./target/release/tpdg \
    --format adoc \
    --output .tmp/verify-e2e-input-data-test-plan-asciidoc/test_cases.adoc \
    --multiple-by-type .type \
    ./data/input_data/verification_methods \
    ./data/input_data/test_case/TEST_PASSING_001.yml \
    ./data/input_data/test_case/TEST_FAILING_002.yml \
    ./data/input_data/test_case/gsma_4.4.2.2_TC.yml \
    ./data/input_data/test_case/gsma_4.4.2.3_TC.yml \
    > .tmp/verify-e2e-input-data-test-plan-asciidoc/stdout1.log 2>&1

sed 's/^\(== \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-input-data-test-plan-asciidoc/test_cases.adoc | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-input-data-test-plan-asciidoc/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-input-data-test-plan-asciidoc/test_cases_fixed.tmp)" > .tmp/verify-e2e-input-data-test-plan-asciidoc/test_cases_fixed.adoc

echo "test_cases_md: |" > .tmp/verify-e2e-input-data-test-plan-asciidoc/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-input-data-test-plan-asciidoc/test_cases_fixed.adoc >> .tmp/verify-e2e-input-data-test-plan-asciidoc/data_with_test_cases.yml
cat ./data/input_data/container/data.yml >> .tmp/verify-e2e-input-data-test-plan-asciidoc/data_with_test_cases.yml

run_test "input-data-test-plan-asciidoc" \
    "./data/input_data/test_plan_output.actual.adoc" \
    "./data/input_data/test_plan_output.expected.adoc" \
    ./target/release/tpdg \
    --format adoc \
    --output ./data/input_data/test_plan_output.actual.adoc \
    --single \
    ./data/input_data/container/schema.json \
    ./data/input_data/container/template_asciidoc.adoc \
    .tmp/verify-e2e-input-data-test-plan-asciidoc/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-input-data-test-plan-asciidoc
echo ""

# Test 7: Input Data AsciiDoc Test Results
echo "========================================"
echo "Test 7: Input Data AsciiDoc Test Results"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-input-data-test-results-asciidoc
./target/release/tpdg \
    --format adoc \
    --output .tmp/verify-e2e-input-data-test-results-asciidoc/test_cases.adoc \
    --multiple-by-type .type \
    ./data/input_data/verification_methods \
    ./data/input_data/test_results/RESULT_TEST_PASSING_001.yml \
    ./data/input_data/test_results/RESULT_TEST_FAILING_002.yml \
    > .tmp/verify-e2e-input-data-test-results-asciidoc/stdout1.log 2>&1

sed 's/^\(== \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-input-data-test-results-asciidoc/test_cases.adoc | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-input-data-test-results-asciidoc/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-input-data-test-results-asciidoc/test_cases_fixed.tmp)" > .tmp/verify-e2e-input-data-test-results-asciidoc/test_cases_fixed.adoc

echo "test_cases_md: |" > .tmp/verify-e2e-input-data-test-results-asciidoc/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-input-data-test-results-asciidoc/test_cases_fixed.adoc >> .tmp/verify-e2e-input-data-test-results-asciidoc/data_with_test_cases.yml
cat ./data/input_data/test_results/container_data.yml >> .tmp/verify-e2e-input-data-test-results-asciidoc/data_with_test_cases.yml

run_test "input-data-test-results-asciidoc" \
    "./data/input_data/test_results_output.actual.adoc" \
    "./data/input_data/test_results_output.expected.adoc" \
    ./target/release/tpdg \
    --format adoc \
    --output ./data/input_data/test_results_output.actual.adoc \
    --single \
    ./data/input_data/test_results/container_schema.json \
    ./data/input_data/test_results/container_template_asciidoc.adoc \
    .tmp/verify-e2e-input-data-test-results-asciidoc/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-input-data-test-results-asciidoc
echo ""

# Test 8: Input Data Markdown Test Results
echo "========================================"
echo "Test 8: Input Data Markdown Test Results"
echo "========================================"
echo ""

mkdir -p .tmp/verify-e2e-input-data-test-results-md
./target/release/tpdg \
    --format md \
    --output .tmp/verify-e2e-input-data-test-results-md/test_cases.md \
    --multiple-by-type .type \
    ./data/input_data/verification_methods \
    ./data/input_data/test_results/RESULT_TEST_PASSING_001.yml \
    ./data/input_data/test_results/RESULT_TEST_FAILING_002.yml \
    > .tmp/verify-e2e-input-data-test-results-md/stdout1.log 2>&1

sed 's/^\(## \(Analysis\|Demonstration\|Inspection\|Test\):\)/\n\n\1/g' .tmp/verify-e2e-input-data-test-results-md/test_cases.md | \
    sed '1{/^$/d;}; 1{/^$/d;}' > .tmp/verify-e2e-input-data-test-results-md/test_cases_fixed.tmp
printf '%s\n' "$(cat .tmp/verify-e2e-input-data-test-results-md/test_cases_fixed.tmp)" > .tmp/verify-e2e-input-data-test-results-md/test_cases_fixed.md

echo "test_cases_md: |" > .tmp/verify-e2e-input-data-test-results-md/data_with_test_cases.yml
sed 's/^/  /' .tmp/verify-e2e-input-data-test-results-md/test_cases_fixed.md >> .tmp/verify-e2e-input-data-test-results-md/data_with_test_cases.yml
cat ./data/input_data/test_results/container_data.yml >> .tmp/verify-e2e-input-data-test-results-md/data_with_test_cases.yml

run_test "input-data-test-results-md" \
    "./data/input_data/test_results_output.actual.md" \
    "./data/input_data/test_results_output.expected.md" \
    ./target/release/tpdg \
    --format md \
    --output ./data/input_data/test_results_output.actual.md \
    --single \
    ./data/input_data/test_results/container_schema.json \
    ./data/input_data/test_results/container_template.j2 \
    .tmp/verify-e2e-input-data-test-results-md/data_with_test_cases.yml

rm -rf .tmp/verify-e2e-input-data-test-results-md
echo ""

# Print summary
echo "=========================================="
echo "SUMMARY"
echo "=========================================="
echo ""
echo "Passed tests: ${#PASSED_TESTS[@]}"
for test in "${PASSED_TESTS[@]}"; do
    echo "  ✓ $test"
done
echo ""

if [ ${#FAILED_TESTS[@]} -gt 0 ]; then
    echo "Failed tests: ${#FAILED_TESTS[@]}"
    for test in "${FAILED_TESTS[@]}"; do
        echo "  ✗ $test"
    done
    echo ""
    echo "Some tests failed. Please review the differences above."
    exit 1
else
    echo "All tests passed! ✓"
    echo ""
    echo "The output files generated by the new CLI interface (--single and --multiple-by-type)"
    echo "match the expected output files, confirming that the refactoring maintains"
    echo "the same behavior as the original --container and --test-case modes."
    exit 0
fi
