= {{ title }}
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:icons: font

[cols="1,3"]
|===
| Document ID | {{ document_id }}
| Version | {{ version }}
| Date | {{ date }}
| Project | {{ project_name }}
{% if author -%}
| Author | {{ author }}
{% endif -%}
| Software Level | {{ software_level }}
|===

<<<

== Document Purpose

This document contains the software verification test cases and procedures for the {{ project_name }}. It defines the specific tests, analyses, and reviews used to verify that the software requirements are correctly and completely implemented.

== Review and Analysis Procedures

=== Review Procedures

*Scope:* {{ review_procedures.scope | strip }}

*Depth:* {{ review_procedures.depth | strip }}

{% if review_procedures.checklists -%}
==== Review Checklists

The following review checklists are used:

{% for checklist in review_procedures.checklists -%}
===== {{ checklist.name }}

{% if checklist.description -%}
{{ checklist.description | strip }}
{% endif %}
{% endfor %}
{% endif %}

{% if analysis_procedures -%}
=== Analysis Procedures

*Scope:* {{ analysis_procedures.scope | strip }}

{% if analysis_procedures.methods -%}
==== Analysis Methods

{% for method in analysis_procedures.methods -%}
===== {{ method.name }}

{{ method.description | strip }}

{% if method.tools -%}
*Tools:* {{ method.tools }}
{% endif %}
{% endfor %}
{% endif %}
{% endif %}

<<<

== Test Overview

=== High-Level Tests

{{ test_overview.high_level_tests | strip }}

=== Low-Level Tests

{{ test_overview.low_level_tests | strip }}

{% if test_overview.test_environment -%}
=== Test Environment

{{ test_overview.test_environment | strip }}
{% endif %}

{% if test_overview.pass_fail_criteria -%}
=== Pass/Fail Criteria

{{ test_overview.pass_fail_criteria | strip }}
{% endif %}

<<<

== Test Cases and Procedures

{{ test_cases_md }}

<<<

== Approval

This Software Verification Cases and Procedures document has been reviewed and approved by:

[cols="1,2,2,1"]
|===
| Role | Name | Signature | Date

| Verification Manager
|
|
|

| Software Manager
|
|
|

| Quality Assurance
|
|
|

|===

<<<

*End of Document*
