[project]
title = "Test Plan Documentation Generator"

[project.config]
dir_for_sdoc_files = "requirements"
output_dir = "requirements/output"

[project.requirements]
include = ["REQUIREMENT", "SECTION"]

[project.requirements.uid]
required = true

[project.traceability]
enable = true

[project.traceability.parent]
field_name = "REFS"
relationship_role = "Parent"

[project.source_code]
paths = ["src"]
